const robotNames = [
    { name: "R2-D2", franchise: "Star Wars" },
    { name: "C-3PO", franchise: "Star Wars" },
    { name: "Terminator", franchise: "Terminator series" },
    { name: "Wall-E", franchise: "Wall-E" },
    { name: "Optimus Prime", franchise: "Transformers" },
    { name: "Ultron", franchise: "Avengers: Age of Ultron" },
    { name: "Data", franchise: "Star Trek: The Next Generation" },
    { name: "HAL 9000", franchise: "2001: A Space Odyssey" },
    { name: "Bender", franchise: "Futurama" },
    { name: "RoboCop", franchise: "RoboCop" },
    { name: "Rosie the Robot", franchise: "The Jetsons" },
    { name: "Johnny 5", franchise: "Short Circuit" },
    { name: "Ava", franchise: "Ex Machina" },
    { name: "T-800", franchise: "Terminator series" },
    { name: "Astro Boy", franchise: "Astro Boy" },
    { name: "B-9", franchise: "Lost in Space" },
    { name: "Marvin", franchise: "The Hitchhiker's Guide to the Galaxy" },
    { name: "Gort", franchise: "The Day the Earth Stood Still" },
    { name: "Bishop", franchise: "Aliens" },
    { name: "David", franchise: "AI: Artificial Intelligence" },
    { name: "K-2SO", franchise: "Rogue One: A Star Wars Story" },
    { name: "Roy Batty", franchise: "Blade Runner" },
    { name: "Sonny", franchise: "I, Robot" },
    { name: "TARS", franchise: "Interstellar" },
    { name: "Gigolo Joe", franchise: "AI: Artificial Intelligence" },
    { name: "Mechagodzilla", franchise: "Godzilla series" },
    { name: "ED-209", franchise: "RoboCop" },
    { name: "Chappie", franchise: "Chappie" },
    { name: "The Iron Giant", franchise: "The Iron Giant" },
    { name: "Tik-Tok", franchise: "Return to Oz" },
    { name: "Baymax", franchise: "Big Hero 6" },
    { name: "T-1000", franchise: "Terminator 2: Judgment Day" },
    { name: "Aibo", franchise: "Sony's robotic pet" },
    { name: "Pris", franchise: "Blade Runner" },
    { name: "Rosie", franchise: "Rosie the Riveter robot" },
    { name: "Gisaku", franchise: "Castle in the Sky" },
    { name: "Mechadon", franchise: "Pacific Rim" },
    { name: "Andrew", franchise: "Bicentennial Man" },
    { name: "Robot B-9", franchise: "Forbidden Planet" },
    { name: "KITT", franchise: "Knight Rider" },
    { name: "H.A.R.D.A.C.", franchise: "Batman: The Animated Series" },
    { name: "Bender", franchise: "Futurama" },
];

export default robotNames;
